function Fresh=mat_run_Fresh(run2extract,filename)
% clear all;
% clc;
%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\mat_run_plantGro\PlantGro.OUT.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/08/12 00:56:03

%% Initialize variables.
i=0;
MAX_X=100;
X= run2extract;%input('which run you want to extract:');
% filename = 'SoilWat.OUT.txt';
while(i<100)
[startRow,endRow] = fname2fresh(X,MAX_X,filename);
if(isnan(startRow)||isnan(endRow))
    X=input('NaN!!!Please try again:\n');
else
        break;
    end
end

% For more information, see the TEXTSCAN documentation.
formatSpec = '%5f%4f%7f%7f%7f%7f%7f%7f%6f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'ReturnOnError', true, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
LL=length(dataArray{1});
for qq=2:length(dataArray)
LL=min(LL,length(dataArray{qq}));
end
for qq=1:length(dataArray)-1
dataArray{qq}=dataArray{qq}(1:LL);
end
Fresh = table(dataArray{1:end-1}, 'VariableNames', {'YEAR','DOY','DAS','DAP','FPWAD','PDMCD','AFPWD','ADPWD','PAGED'});

%% Clear temporary variables
clearvars filename startRow endRow formatSpec fileID dataArray ans i MAX_X;