function PlantGro=mat_run_plantGro(run2extract,filename)
% clear all;
% clc;
%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\mat_run_plantGro\PlantGro.OUT.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/08/12 00:56:03

%% Initialize variables.
i=0;
MAX_X=100;
X = run2extract;%input('which run you want to extract:');
while(i<100)
[startRow,endRow] = fname1gro(X,MAX_X,filename);
    if(isnan(startRow)||isnan(endRow))
        X=input('NaN!!!Please try again:\n');
    else
        break;
    end
end

% For more information, see the TEXTSCAN documentation.
% filename = 'PlantGro.OUT.txt';
formatSpec = '%5f%4f%6f%6f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%7f%9f%7f%7f%7f%8f%8f%8f%8f%8f%8f%8f%8f%7f%7f%7f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
PlantGro = table(dataArray{1:end-1}, 'VariableNames',{'YEAR','DOY','DAS','DAP',...
    'L#SD','GSTD','LAID','LWAD','SWAD','GWAD','RWAD','VWAD','CWAD','G#AD',...
    'GWGD','HIAD','PWAD','P#AD','WSPD','WSGD','NSTD','PST1A','PST2A','KSTD',...
    'EWSD','LN%D','SH%D','HIPD','PWDD','PWTD','SLAD','CHTD','CWID','NWAD','RDPD',...
    'RL1D','RL2D','RL3D','RL4D','RL5D','RL6D','RL7D','RL8D','SNW0C','SNW1C'});

%% Clear temporary variables
clearvars filename startRow endRow formatSpec fileID dataArray ans i MAX_X;